.github/workflows/build.yml
.travis.yml
README.md

I noticed that IceFireDB readme badges seem to be not working.

docs: readme badge fix

---

.github/workflows/test.yml
conn_test.go
driver/oss/db.go
driver/oss/iterator.go
driver/oss/s3.go
driver/oss/singularity.go
driver/oss/snapshot.go
driver/oss/write_batch.go
flags.go
go.mod
go.sum
hashes_test.go
lists_test.go
main.go
s3_test.go
scan_test.go
set_test.go
sorted_sets_test.go
strings_test.go

Hi! Added oss engine to IceFireDB.

driver: added oss engine 

---

.github/workflows/test.yml
driver/ipfs/db.go
driver/orbitdb/db.go
driver/orbitdb/iterator.go
driver/orbitdb/write_batch.go

[bug-fix] : Fixed the bug of orbit engine, and added CI test to orbit and IPFs

---

.github/workflows/test.yml

feat(workflows): Add push phase test ci

feat(workflows): Add push phase test ci

---

IceFireDB-SQLProxy/config/config.yaml
IceFireDB-SQLProxy/internal/mysql/handle.go
IceFireDB-SQLProxy/pkg/mysql/server/command.go
IceFireDB-SQLite/README.md
IceFireDB-SQLite/internal/mysql/handle.go
IceFireDB-SQLite/internal/mysql/proxy.go
IceFireDB-SQLite/internal/mysql/server.go
IceFireDB-SQLite/internal/sqlite/db.go
IceFireDB-SQLite/pkg/config/config.go

- Config bug
- Fix Sqlproxy stmt bug
- Add Golang Gorm support for Sqlite
- Fix Readme

Fix sqlprox bug and add some support of sqlite

---

README.md

feat(redis):support redis proxy mode

feat(redis):support redis proxy mode

---

.github/workflows/build.yml

feat(ci):support pubsub && redis-proxy build

feat(ci):support pubsub && redis-proxy build

---

IceFireDB-PubSub/LICENSE
IceFireDB-Redis-Proxy/LICENSE
IceFireDB-SQLProxy/LICENSE
IceFireDB-SQLite/LICENSE
LICENSE

feat(license):Update open source license to MIT

feat(license):Update open source license to MIT

---

go.mod

Signed-off-by: Oct <qianggeek@gmail.com>

feat(mod): del ipfs-log replace

---

README.md

feat(doc):upgrade project readme

feat(doc):upgrade project readme

---

server_info.go

fix: data race for metrics when return server info

---

strings.go
strings_test.go

The modified code achieves the same effect as the redis exists command.

fix: support multi keys exists

---

README.md

1. **Integration with NATS for High-Performance Decentralized Networking:**
We've integrated with [NATS](https://nats.io/) to establish a high-performance decentralized networking layer. This integration significantly improves edge network efficiency and reliability, enabling faster and more reliable communication between nodes in distributed systems.
2. **Support for KV and SQL Immutable Storage Engine:**
Our system now supports a combination of KV and SQL immutable storage engines, leveraging the capabilities of the [immudb](https://github.com/codenotary/immudb) storage engine. This ensures tamper-resistant and auditable data storage, enhancing data integrity and security across the platform.
These enhancements strengthen our system's performance, security, and reliability, making it …

feat(roadmap):update roadmap

---

IceFireDB-PubSub/pkg/ppubsub/pubsubStore.go

chore(icefiredb-pubsub): update pubsubStore.go

---

IceFireDB-SQLite/README.md
IceFireDB-SQLite/SQLTest.md

feat(sqlite):update sqlite docs
-  modified: IceFireDB-SQLite/README.md
-  modified: IceFireDB-SQLite/SQLTest.md

feat(sqlite):update sqlite docs

---

strings.go

Optimize cmdGET for RESP GET protocol compliance
Updated the function to return nil for non-existing keys without error, handle empty string values correctly, and improve error handling for other cases.

feat(cmdGET):upgrade GET command

---

strings.go

feat(command): update GETRANGE command
- Updated the `cmdGETRANGE` function to handle argument validation and error handling more robustly.
- Ensured the function checks for the correct number of arguments and returns appropriate errors for invalid indices.
- Integrated the underlying `ldb.GetRange` implementation to handle range retrieval with proper boundary and negative index checks.
- Ensured the function returns an empty string for nil values to align with RESP protocol behavior.

feat(command):update GETRANGE command

---

strings.go

Updated the `cmdTTL` function to align with the RESP TTL command protocol:
- Returns remaining TTL in seconds for keys with expiration.
- Returns -1 for keys without expiration.
- Returns -2 for non-existent keys.

feat(cmdTTL):upgrade cmdTTL

---

strings.go

This PR enhances `cmdSETBIT` for full compliance with  RESP standards, focusing on robustness and input validation.
**Key Changes:**
* **Input Validation:**
* Enforces non-negative `offset` values, returning an error for invalid inputs.
* Validates that `value` is either 0 or 1, with an error for other values.
* **Error Handling:**
* Provides more informative error messages for invalid input types.

feat(CMD_SETBIT): Align SETBIT command with RESP protocol standards

---

IceFireDB-SQLProxy/pkg/mysql/server/conn.go
IceFireDB-SQLite/pkg/mysql/server/conn.go

make function comment match function name

chore: make function comment match function name

---

IceFireDB-SQLProxy/pkg/mysql/client/auth.go
IceFireDB-SQLProxy/pkg/mysql/mysql/resultset_helper.go
IceFireDB-SQLite/pkg/mysql/client/auth.go
IceFireDB-SQLite/pkg/mysql/mysql/resultset_helper.go

chore: fix some typos in comment

---

IceFireDB-PubSub/test/redis.go
IceFireDB-Redis-Proxy/test/redis.go
IceFireDB-SQLProxy/pkg/mysql/client/pool.go
IceFireDB-SQLProxy/pkg/mysql/mysql/mysql_gtid.go
IceFireDB-SQLite/pkg/mysql/client/pool.go
IceFireDB-SQLite/pkg/mysql/mysql/mysql_gtid.go

use the built-in max/min to simplify the code and format some comments

refactor: use the built-in max/min to simplify the code

---

IceFireDB-SQLProxy/README.md
IceFireDB-SQLProxy/config/config.yaml
IceFireDB-SQLProxy/internal/mysql/handle.go
IceFireDB-SQLProxy/internal/mysql/p2p.go
IceFireDB-SQLProxy/internal/mysql/proxy.go
IceFireDB-SQLProxy/internal/mysql/server.go
IceFireDB-SQLProxy/pkg/config/config.go
IceFireDB-SQLProxy/pkg/mysql/client/auth.go
IceFireDB-SQLProxy/pkg/mysql/mysql/result.go
IceFireDB-SQLProxy/pkg/mysql/mysql/resultset.go
IceFireDB-SQLProxy/pkg/p2p/pubsub.go

Repair the project so that it can run normally

fix:config.yaml and config.go

---

lists.go

- Add key-based mutex synchronization to prevent race conditions in hybriddb environment
- Fix intermittent test failures where list length was inconsistent due to cache timing issues
- Maintain TTL preservation when source and destination lists are identical

fix(hybriddb): ensure atomic RPOPLPUSH operations with key-based mutex locking
